
name: Build and Run Docker

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build docker
      run: |
        docker build -t ping_central .
    - name: Run docker
      run: |
        docker run ping_central
            
